# Generated by Django 5.1.15 on 2026-10-03 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltSprayCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('blister_grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('inspected_at', models.DateTimeField()),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salt_spray_coupons', to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salt_spray_coupons', to='core.clothroll')),
            ],
            options={
                'ordering': ['roll_id', 'coupon_no'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('roll', 'coupon_no'), name='uniq_active_coupon_no_per_roll')],
            },
        ),
    ]
